---
apiVersion: v1
kind: List
items:
- apiVersion: capabilities.3scale.net/v1beta1
  kind: Product
  metadata:
    annotations:
      3scale_toolbox_created_at: '2023-09-13T07:59:52Z'
      3scale_toolbox_version: 0.20.0
    name: hello.service.kurzpxbe
  spec:
    name: hello-service API (v1.0.0-SNAPSHOT)
    systemName: hello_service
    description: 
    mappingRules:
    - httpMethod: GET
      pattern: "/hello/get$"
      metricMethodRef: gethelloget
      increment: 1
      last: false
    - httpMethod: GET
      pattern: "/hello/get/{name}$"
      metricMethodRef: gethellogetname
      increment: 1
      last: false
    metrics:
      hits:
        friendlyName: Hits
        unit: hit
        description: Number of API hits
    methods:
      gethelloget:
        friendlyName: gethelloget
        description: ''
      gethellogetname:
        friendlyName: gethellogetname
        description: ''
      alertuser:
        friendlyName: alertUser
        description: ''
    policies:
    - name: apicast
      version: builtin
      configuration: {}
      enabled: true
    - name: routing
      version: builtin
      configuration:
        rules:
        - condition:
            combine_op: and
            operations:
            - value_type: plain
              match: header
              value: Hello*
              op: matches
              header_name: MY-HEADER
          url: http://hello-service.backend-api.svc.cluster.local:8080
          replace_path: "/hello/get"
      enabled: true
    applicationPlans:
      plan1:
        name: plan1
        appsRequireApproval: false
        trialPeriod: 5
        setupFee: 5.0
        custom: false
        state: hidden
        costMonth: 10.0
        pricingRules:
        - from: 1
          to: 1000
          pricePerUnit: 0.5
          metricMethodRef:
            systemName: alertuser
        - from: 1001
          to: 10000
          pricePerUnit: 0.3
          metricMethodRef:
            systemName: alertuser
        - from: 10001
          to: 1000000
          pricePerUnit: 0.2
          metricMethodRef:
            systemName: hits
        limits:
        - period: eternity
          value: 10000
          metricMethodRef:
            systemName: alertuser
        - period: month
          value: 10000
          metricMethodRef:
            systemName: alertuser
        - period: week
          value: 1000
          metricMethodRef:
            systemName: alertuser
        - period: day
          value: 100
          metricMethodRef:
            systemName: hits
    backendUsages:
      hello_service:
        path: "/"
    deployment:
      apicastSelfManaged:
        authentication:
          userkey:
            authUserKey: user_key
            credentials: query
            security:
              hostHeader: 
              secretToken: Shared_secret_sent_from_proxy_to_API_backend_acb193e8401ac2bd
            gatewayResponse:
              errorStatusAuthFailed: 403
              errorHeadersAuthFailed: text/plain; charset=us-ascii
              errorAuthFailed: Authentication failed
              errorStatusAuthMissing: 403
              errorHeadersAuthMissing: text/plain; charset=us-ascii
              errorAuthMissing: Authentication parameters missing
              errorStatusNoMatch: 404
              errorHeadersNoMatch: text/plain; charset=us-ascii
              errorNoMatch: No Mapping Rule matched
              errorStatusLimitsExceeded: 429
              errorHeadersLimitsExceeded: text/plain; charset=us-ascii
              errorLimitsExceeded: Usage limit exceeded
        stagingPublicBaseURL: http://hello-staging-apicast.apps.cluster-bt5c8.bt5c8.sandbox1023.opentlc.com:80
        productionPublicBaseURL: http://hello-production-apicast.apps.cluster-bt5c8.bt5c8.sandbox1023.opentlc.com:80
- apiVersion: capabilities.3scale.net/v1beta1
  kind: Backend
  metadata:
    annotations:
      3scale_toolbox_created_at: '2023-09-13T07:59:53Z'
      3scale_toolbox_version: 0.20.0
    name: hello.service.wqyxukie
  spec:
    name: hello-service API (v1.0.0-SNAPSHOT) Backend
    systemName: hello_service
    privateBaseURL: http://hello-service.backend-api.svc.cluster.local:8080
    description: Backend of hello-service API (v1.0.0-SNAPSHOT)
    mappingRules: []
    metrics:
      hits:
        friendlyName: Hits
        unit: hit
        description: Number of API hits
    methods: {}
