apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: hello-apicast-staging
  namespace: threescale-apicast
spec:
  adminPortalCredentialsRef:
    name: 3scaleportal
  deploymentEnvironment: staging
  configurationLoadMode: lazy
  exposedHost:
    host: "hello-staging-apicast.apps.cluster-bt5c8.bt5c8.sandbox1023.opentlc.com"


---

apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: hello-apicast-production
  namespace: threescale-apicast
spec:
  adminPortalCredentialsRef:
    name: 3scaleportal
  deploymentEnvironment: production
  configurationLoadMode: lazy
  exposedHost:
    host: "hello-production-apicast.apps.cluster-bt5c8.bt5c8.sandbox1023.opentlc.com"